### ISSUE TITLE
自建后端卖舍友功能异常

### ISSUE THREAD

**Issue by zR00t1** [oubingbing/wechatAlliance#19]
后端是自建的，拉取的最新源码，各项配置没有问题，表白墙和其他功能都可以正常使用，但是卖舍友功能有问题，在前端调试的时候发现图片可以正常上传到七牛云的OSS，但是未写入到数据库中，排查了好几天不知道哪里出问题了，还得请叶子哥和其他师傅帮忙解决下，谢谢师傅们了
![image](https://user-images.githubusercontent.com/46400438/70371271-e83f0400-190b-11ea-92c6-f5001b716067.png)
![image](https://user-images.githubusercontent.com/46400438/70371276-f3922f80-190b-11ea-8f06-2d0fe6e20217.png)

**Comment by oubingbing** [comment]
在.env文件里面加入这个参数QI_NIU_DOMAIN=https://image.geekpeople.top，当然，参数值是你自己的七牛域名，记得加http

**Comment by zR00t1** [comment]
谢谢叶子哥，宁昨天在群里已经给我解决了
