### ISSUE TITLE
安装过程中踩的坑

### ISSUE THREAD

**Issue by xingye1997** [oubingbing/wechatAlliance#5]
宝塔的教程不完整，
宝塔最新版的 需要删除几个被禁用的函数 需要安装PHP扩展，。
还有就是 安装后 怎么进入后台。

**Comment by oubingbing** [comment]
好的，谢谢，进入后台输入你的网站域名，然后注册一个小程序的账号就能进入管理后台了

**Comment by xingye1997** [comment]
您好  叶子

是这样的，我部署的后台注册账号时 用了smtp 邮箱

和www.sendcloud.net的发件API   可是 都收不到 注册邮件

[image: image.png]

[image: image.png]
然后我去数据库更改了注册状态


发现 设置小程序后台时没有学校可选
再去 数据库  手动添加了 学校
注册了小程序
在部署小程序后 发现图片不能上传

在后台配置文件中填了七牛 key  和空间名    空间属性是私有的
微信后台中 配置了如下域名  BB.dr1997.com 是后台名 cdn.61dz.com 是空间  绑定的域名
[image: image.png]

在小程序配置页面 设置了七牛的域名 CDN.61dz.com
[image: image.png]

[image: image.png]

请问 是哪里没设置 好吗？




叶子 <notifications@github.com> 于2019年6月10日周一 上午10:45写道：

**Comment by zR00t1** [comment]
您好，我使用宝塔搭建起来了这个后台，中间所以东西都安装成功了，env的配置文件也是正常的，但是打开网站显示403，nginx没有错误日志，且网站目录下都给了755权限，请问您遇到过这个问题吗

**Comment by oubingbing** [comment]
@zR00t1 我也不清楚，应该是nginx路径配置的问题，我可以帮你问一下用这种方式安装的人

**Comment by zR00t1** [comment]
谢谢叶子哥了，是权限的问题，我已经解决了，非常感谢
