### ISSUE TITLE
宝塔部署完了，403。

### ISSUE THREAD

**Issue by a465855787** [oubingbing/wechatAlliance#7]
按照教程一步步走的，就是不行。

**Comment by kissgeek** [comment]
宝塔部署错误可以参考宝塔官网教程。

**Comment by tuzimoe** [comment]
<img width="613" alt="螢幕快照 2019-06-25 下午7 30 57" src="https://user-images.githubusercontent.com/17731805/60078338-dd3e5000-977f-11e9-8aae-237d9f8f550e.png">

**Comment by kissgeek** [comment]
在宝塔里面设置网站根目录
![{1T{~% AD5F{~9{MWCG88KG](https://user-images.githubusercontent.com/34683107/60084040-5da58680-9769-11e9-891e-60d68e0e8419.png)

**Comment by tuzimoe** [comment]
运行目录选择 /public 试试

**Comment by kissgeek** [comment]
安装PHP的laravel框架 composer install ，遇到过吗？
![W53R(}M 3EU HM0P@HE I}4](https://user-images.githubusercontent.com/34683107/60100420-488e1f00-978c-11e9-9e16-408acb7329a0.png)

**Comment by tuzimoe** [comment]
耐心等待， 如果是国内服务器可食用 
https://pkg.phpcomposer.com/

**Comment by kissgeek** [comment]
安装PHP的laravel框架时报这样的错误 composer install，能不能帮忙看一下。
![DPIF3W9`34OPEZ)N2U)07`9](https://user-images.githubusercontent.com/34683107/60102104-a40ddc00-978f-11e9-96f1-2accace5f051.png)
![WB~3G$U9M2JIU4_S_5U58 4](https://user-images.githubusercontent.com/34683107/60102129-ad974400-978f-11e9-92d2-84c15f985899.png)

**Comment by tuzimoe** [comment]
<img width="666" alt="螢幕快照 2019-06-26 上午8 40 17" src="https://user-images.githubusercontent.com/17731805/60131687-0d243c80-97ee-11e9-84bd-c215f2e1c6e7.png">
在这里取消禁用函数 proc_open

**Comment by kissgeek** [comment]
生成appkey
php artisan key:generate  出现错误
![1AFC584716EA9A73322134B64702B04E](https://user-images.githubusercontent.com/34683107/60142271-9d14b700-97eb-11e9-964a-6cb658d311c3.png)

**Comment by tuzimoe** [comment]
建议检查 .env

**Comment by kissgeek** [comment]
@a465855787 请问一下你403错误解决了吗？知不知道具体原因

**Comment by a465855787** [comment]
[root@VM_0_15_centos xiaoqingshu]# php artisan key:generate

[root@VM_0_15_centos xiaoqingshu]# php artisan jwt:secret

 This will invalidate all existing tokens. Are you sure you want to override the secret key? (yes/no) [no]:
 > yes

jwt-auth secret [**************] set successfully.
[root@VM_0_15_centos xiaoqingshu]# cd vendor/

[root@VM_0_15_centos xiaoqingshu]# cd ..
.
[root@VM_0_15_centos wwwroot]# chown -R www:www xiaoqingshu/
chown: changing ownership of ‘xiaoqingshu/public/.user.ini’: Operation not permitted
[root@VM_0_15_centos wwwroot]# cd xiaoqingshu/
[root@VM_0_15_centos xiaoqingshu]# chmod -R 755 storage/logs/
[root@VM_0_15_centos xiaoqingshu]#

**Comment by a465855787** [comment]
先把运行目录设置成public，然后再执行上面那些命令就行了
